### ISSUE TITLE
Make examples async

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz-topics/panel-chat-examples#39]
Its *best practice* to use `async` functions and methods for chat interfaces. This would also help us when we deploy them.

I can see some examples use *sync* `sleep` or `openai` methods. One example is echo_stream.py. We should convert them to `async` examples.

**Comment by ahuang11** [comment]
I'm hesitant about converting all the examples to asynchronous code since it's not required to use ChatInterface, and some individuals, myself included a few years back, may not be familiar with async programming and might lose interest or become perplexed when encountering async code.

I'd be happy to add `echo_stream_async.py` as an example though.

**Comment by MarcSkovMadsen** [comment]
Ok. Thats is a good idea.
